name: very_good_slide_puzzle
description: A Very Good Project created by Very Good CLI.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"
  flutter: 2.8.0

dependencies:
  bloc: ^8.0.1
  equatable: ^2.0.3
  fake_async: ^1.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.0
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^0.23.0+1
  gap: ^2.0.0
  google_fonts: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  bloc_test: ^9.0.1
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0
  very_good_analysis: ^2.4.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: assets/fonts/GoogleSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/GoogleSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/GoogleSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/GoogleSans-Italic.ttf
          weight: 400
          style: italic
